## $$MDSC-202(P)$$

### $$Assignment-I$$

### *Author: Akula Venkata Satya Sai Gopinadh*

### *Date:17-02-2023*

## MATRIX OPERATIONS

```{r}
A <- matrix(data=c(-1,2,5,-71),nrow=2,ncol=2)
A

```

## MATRIX STUCTURES

### 1. Arrangement of Elements by ROWS:

```{r}
B <- matrix(data=c(1,2,3,4,5,6),nrow=3,ncol=2,byrow = FALSE)
B
```

### 2.Arrangement of Elements by COLUMNS:

```{r}
C <- matrix(data=c(1,2,3,4,5,6,7,8,9),nrow=3,ncol=3,byrow = TRUE)
C
```

### 3. Using rbind function:

```{r}
D <- rbind(1:4,5:8)
D
```

### 4.Using cbind function:

```{r}
E <- cbind(c(1,2),c(3,4),c(5,6),c(7,8))
E
```

## Misc. Operations:

```{r}
# lets start:
```

```{r}
mat <- rbind(c(-1,7,48,65),4:7,c(100,101,102,108),15:18)
mat
```

```{r}
dim(mat)
```

```{r}
nrow(mat)
ncol(mat)

```

```{r}
dim(mat)[1]
```

#Let's Take another matrix of order 3\*3 for further operations:

```{r}
F <- matrix(data=c(-0.57,54,8,0.6,-5,9,0.75,-12,15),nrow=3,ncol=3)
F
```

```{r}
diag(x=F)# Extracting Diagonal Elements
```

```{r}
F[3,2] # extracting element from particular position
```

```{r}
F[1,] # Extracting first row
```

```{r}
F[,3] #Extracting third column
```

```{r}
F[2:3,] # Extracting second and third rows
```

```{r}
F[,1:2] # Extracting first and second columns
```

```{r}
F[,c(3,1)] # Gives the coumns of the matrix in order of first third column then first column
```

```{r}
F[c(2,1),] # Gives the rows first second row then the first row.
```

```{r}
F[c(3,1),2:3] # Giving the values of third row and first row respectively leaving first column
```

```{r}
F[,-2] # removes 2nd column
```

```{r}
F[-1,] # removes first row.
```

```{r}
F[-1,3:2] # removes first row and prints 3 and 2 columns respectively.
```

```{r}
F[-1,-2]
# Removes first row and second column
```

```{r}
F[-1,-c(2,3)] # removes first row and removes second and third columns also and gives values.
```

```{r}
F[2,]<-1:3
F
```

```{r}
F[c(1,3), 2] <- 108
F
 # elemnt of first and third row of secind col is changed to 108
```

```{r}
F[3,]<-F[,3]
F #  Third col is exchanged with 3rd row.
```

```{r}
F[c(1,3),2:1] <- c(1,-1,20,-20)
F
```

```{r}
F[c(1,3),c(1,3)] <- c(-2,2)
F

```

```{r}
diag(x= F) <- rep(x= 0 ,times =3)
F

```

```{r}

```
